### ISSUE TITLE
Do you have any plan to release the Discriminator weights for 256 and 512 models?

### ISSUE THREAD

**Issue by qilimk** [ajbrock/BigGAN-PyTorch#18]
Hi ajbrock,
Do you have any plan to release the discriminator weights for 256 or 512 models? I tried to use the discriminator for 128 models and I think it is a conditional discriminator. Is there any chance to convert it to an unconditional discriminator? Please correct me if I misunderstand anything about it. 
Thank so much!

**Comment by ajbrock** [comment]
Hi qilimk,

We are currently considering training and releasing a 256x256 model using this repo, but have not made any decisions yet. The discriminators are conditional, but you could conceivably remove the projection layer to make it unconditional (it's not clear how much this will impact the network, however, you'd have to figure that out for yourself.)

**Comment by qilimk** [comment]
Do you consider to release the weights of TensorFlow version discriminator for the 256x256 or 512x512 models? Thanks.

**Comment by ajbrock** [comment]
There are no plans to release the TF versions of the discriminator weights at this time.
