### ISSUE TITLE
Any reason you don't zero optimizer between Discriminator training steps?

### ISSUE THREAD

**Issue by monney** [ajbrock/BigGAN-PyTorch#25]
WGAN-GP and most other gans I've seen will call D_optim.zero_grad() between Discriminator iterations. Is there any reason you don't? Does it provide better performance?

**Comment by monney** [comment]
Just to be clear I'm referring to calling between the multiple steps taken per G step

**Comment by ajbrock** [comment]
Good catch--this was a typo! Fixed with the most recent commit. Note that this will not affect the results for the main training script since we by default train with `num_D_steps=1`
