### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by hanshan1** [ajbrock/BigGAN-PyTorch#27]
Hi,i met the question: unable to open file: name = 'data/ILSVRC128.hdf5',error message = 'No such file or directory', flags = 0, o_flags = 0).

**Comment by isaac-dunn** [comment]
Have you read the README section 'How To Use This Code'?
Either replace `--dataset I128_hdf5` with `--dataset I128` in the script to launch training, or first run the `prepare_data.sh` script. Whichever you choose, make sure you have got the ImageNet dataset downloaded: by default, `data/ImageNet` should contain the 1000 directories of images for the 1000 classes.
