### ISSUE TITLE
Using grayscale input images instead of RGB.

### ISSUE THREAD

**Issue by kseuro** [ajbrock/BigGAN-PyTorch#29]
Hello @ajbrock! Thank you so much for making your model available for others to use. I'm trying to re-purpose it at the moment for a research project.

I have a two-fold issue: one piece is data-related, the other architecture-related.

1) I am trying to use a dataset of .png grayscale images produced by an analogue-to-digital converter. The image dimensions are 512x512 and there is only 1 class. I have made the following modifications in order to get the dataset loaded: (larcv is the dataset name)

In `utils.py`
```
# Convenience dicts
dset_dict = {'larcv_png': dset.ImageFolder, 'larcv_hdf5': dset.ILSVRC_HDF5,
             'I32': dset.ImageFolder, 'I64': dset.ImageFolder,
             'I128': dset.ImageFolder, 'I256': dset.ImageFolder,
             'I32_hdf5': dset.ILSVRC_HDF5, 'I64_hdf5': dset.ILSVRC_HDF5,
             'I128_hdf5': dset.ILSVRC_HDF5, 'I256_hdf5': dset.ILSVRC_HDF5,
             'C10': dset.CIFAR10, 'C100': dset.CIFAR100}
imsize_dict = {'larcv_png': 512, 'larcv_hdf5': 512,
               'I32': 32, 'I32_hdf5': 32,
               'I64': 64, 'I64_hdf5': 64,
               'I128': 128,
               'I128_hdf5': 128,
               'I256': 256, 'I256_hdf5': 256,
               'C10': 32, 'C100': 32}
root_dict = {'larcv_png': 'larcv_png', 'larcv_hdf5': 'ILSVRC512.hdf5',
             'I32': 'ImageNet', 'I32_hdf5': 'ILSVRC32.hdf5',
             'I64': 'ImageNet', 'I64_hdf5': 'ILSVRC64.hdf5',
             'I128': 'ImageNet', 'I128_hdf5': 'ILSVRC128.hdf5',
             'I256': 'ImageNet', 'I256_hdf5': 'ILSVRC256.hdf5',
             'C10': 'cifar', 'C100': 'cifar'}
nclass_dict = {'larcv_png': 1, 'larcv_hdf5': 1,
               'I32': 1000, 'I32_hdf5': 1000,
               'I64': 1000, 'I64_hdf5': 1000,
               'I128': 1000, 'I128_hdf5': 1000,
               'I256': 1000, 'I256_hdf5': 1000,
               'C10': 10, 'C100': 100}
# Number of classes to put per sample sheet
classes_per_sheet_dict = {'larcv_png': 1, 'larcv_hdf5': 1,
                          'I32': 50, 'I32_hdf5': 50,
                          'I64': 50, 'I64_hdf5': 50,
                          'I128': 20, 'I128_hdf5': 20,
                          'I256': 20, 'I256_hdf5': 20,
                          'C10': 10, 'C100': 100}
```

The dataset does serialize and load successfully, but when I check the dimensions of the images inside of the `ILSVRC_HDF5`class in `datasets.py` using `img.shape`, the dimensions show as `[3, 512, 512]`. 

This leads to a size-mismatch in the forward function of G_D at the line:
`D_input = torch.cat([G_z, x], 0) if x is not None else G_z` where `G_z.shape = [4, 1, 512, 512]` and `x.shape = [4, 3, 512, 512]`

2) I've made the following changes to the `D_arch` dictionary in order to accommodate the 512x512 images:

```
  arch[512] = {'in_channels' :  [1] + [ch*item for item in [1, 2, 4, 8, 8, 16, 16]],
               'out_channels' : [item * ch for item in [1, 2, 4, 4, 8, 8, 16, 16]],
               'downsample' : [True] * 7 + [False],
               'resolution' : [512, 256, 128, 64, 32, 16, 8, 4],
               'attention' : {2**i: 2**i in [int(item) for item in attention.split('_')]
                              for i in range(2,10)}}
```

I have also modified the last layer of the Generator to output 1-channel images:

```
    # output layer: batchnorm-relu-conv.
    # Consider using a non-spectral conv here
    self.output_layer = nn.Sequential(layers.bn(self.arch['out_channels'][-1],
                                                cross_replica=self.cross_replica,
                                                mybn=self.mybn),
                                    self.activation,
                                    self.which_conv(self.arch['out_channels'][-1], 1))
```

My questions are:

- How can I get the images to load with only 1 channel?
- Are the architecture modifications I've made appropriate?

Thank you so much.

**Comment by ajbrock** [comment]
The architecture modifications should be sufficient, but I'm guessing you're not handling the dataset properly. Make sure the outputs of the dataset itself are actually single channel first (you'll probably also need to modify the dataloader transforms in `utils.py`, as those all use three-channel inputs for norm_mean and norm_std. I'm guessing that even though your PNGs are greyscale they might still be loaded by the `ImageFolder` dataset as three-channel images where all three channels are the same. Make sure your data is correct first!

Regardless, if you want to use the HDF5 you'll also need to make sure the HDF5 you're producing from your dataset has only 1 channel. [These lines](https://github.com/ajbrock/BigGAN-PyTorch/blob/master/make_hdf5.py#L86-L87) have a 3 in the channel dim for the `max_shape` and `chunk` args.

You might also consider training on the non-HDF5 version of the dataset to make sure you're loading single-channel images before producing the HDF5.

**Comment by kseuro** [comment]
Thanks for the quick response. 

I've made the changes to the `max_shape` and `chunks` arguments and changed the data loader transforms in `utils.py` to `norm_mean,  norm_std  = [0.5], [0.5].` 

I tried to check whether I'm actually loading single-channel images by running the non-HDF5 version by using the flag `--dataset larcv_png` in the launch script. The `ImageFolder` loads a numpy array of strings where each string is a full path to a training image. That is, `imgs.shape: (400,2)`. The routine then fails at `return transforms.functional.center_crop(img, min(img.size))` in `utils.py` with the message: `TypeError: 'int' object is not iterable`.

I'm apologize if I've missed something here but I am unsure of how to proceed.

**Comment by kseuro** [comment]
Update: 

I changed the line: 
`path, target = self.transform(imgs[index][0]), imgs[index][1]` in `ImageFolder` to 
`path, target = imgs[index][0], imgs[index][1]`. This allows the PNG data to load as PIL images. 

However, this change caused an error at `for n, item in enumerate(items):` in the `progress` function in `utils.py`. `item` is expected to be a torch tensor but is a PIL image instead. I found that this problem occurred because the image transforms were not being applied inside of the `__getitem__` attribute in the `ImageFolder` class because [this line](https://github.com/ajbrock/BigGAN-PyTorch/blob/45be0dc1f78d61cb430ff16f683d3fc6906d79e5/datasets.py#L157) is indented too far. I fixed the indent and the model began training.

Hope this is helpful.

**Comment by nassarofficial** [comment]
@kseuro how did you load your own dataset?

**Comment by kseuro** [comment]
@nassarofficial From the readme, do the following:

"To prep your own dataset, you will need to add it to datasets.py and modify the convenience dicts in utils.py (dset_dict, imsize_dict, root_dict, nclass_dict, classes_per_sheet_dict) to have the appropriate metadata for your dataset. Repeat the process in prepare_data.sh (optionally produce an HDF5 preprocessed copy, and calculate the Inception Moments for FID)."

You can see the modifications I made for my dataset in my original post. If your images are larger than 256x256, you'll have to modify the discriminator architecture accordingly.
