### ISSUE TITLE
Use my own dataset

### ISSUE THREAD

**Issue by LIMr1209** [ajbrock/BigGAN-PyTorch#30]
If I use my own data set, do I need to use my own data set to train an inception_v3 when I get the initial measurement?

**Comment by LIMr1209** [comment]
Do I need to ensure that class_to_idx is the same for biggan and inception_v3?

**Comment by ajbrock** [comment]
1. It's typically better to use a classifier trained on the dataset of interest, but the imagenet inceptionv3 is reasonably robust for getting rough metrics
2. There's no need for these things to match up, please look at the definition of the inception score and FID.

**Comment by LIMr1209** [comment]
Need to modify num_classes of inception_v3 @ajbrock
