### ISSUE TITLE
A GPU VRAM is 6. Can it be trained?

### ISSUE THREAD

**Issue by LIMr1209** [ajbrock/BigGAN-PyTorch#31]
When I set batch_size to 8, num_G_accumulations to 256, num_D_accumulations to 256, it still remains CUDA out of memory.

**Comment by ajbrock** [comment]
You have to be able to fit the model, any EMA copies, and all of the activations for your given batch size into memory. It's also not clear that batch size of 8 per device will be sufficient for BatchNorm in G. I'm afraid this is not really a model for small hardware.
