### ISSUE TITLE
A mismatch problem on fine-tune

### ISSUE THREAD

**Issue by chensln** [ajbrock/BigGAN-PyTorch#32]
Hi, I tried to fine-tune pre-trained model on my dataset, but the following error raised, which probably means a mismatch on the number of classes between imagenet(1000) and my dataset(2). So, Is there any suggestion on fine-tune for a different number of classes. Thanks.

RuntimeError: Error(s) in loading state_dict for Generator:
size mismatch for shared.weight: copying a param with shape torch.Size([1000, 128]) from checkpoint, the shape in current model is torch.Size([2, 128]).

**Comment by ajbrock** [comment]
I'd recommend either (a) selecting your own embeddings if you have them a priori, (b) selecting the two imagenet classes which are closest to your dataset classes [or perhaps interpolating between several classes if you feel adventurous] or (c) initializing the embeddings from scratch. There are almost certainly other strategies one could come up with though, don't let these limit you.

**Comment by VictorZuanazzi** [comment]
Hi,

I am trying to load the pre-trained model as well. I am having a similar issue, but regarding another tensor:
`RuntimeError: Error(s) in loading state_dict for Generator:
	size mismatch for blocks.0.0.bn1.gain.weight: copying a param with shape torch.Size([1536, 148]) from checkpoint, the shape in current model is torch.Size([1000, 1536]).
	size mismatch for blocks.0.0.bn1.bias.weight: copying a param with shape torch.Size([1536, 148]) from checkpoint, the shape in current model is torch.Size([1000, 1536]).
	size mismatch for blocks.0.0.bn2.gain.weight: copying a param with shape torch.Size([1536, 148]) from checkpoint, the shape in current model is torch.Size([1000, 1536]).
	size mismatch for blocks.0.0.bn2.bias.weight: copying a param with shape torch.Size([1536, 148]) from checkpoint, the shape in current model is torch.Size([1000, 1536]).
	size mismatch for blocks.1.0.bn1.gain.weight: copying a param with shape torch.Size([1536, 148]) from checkpoint, the shape in current model is torch.Size([1000, 1536]).
	size mismatch for blocks.1.0.bn1.bias.weight: copying a param with shape torch.Size([1536, 148]) from checkpoint, the shape in current model is torch.Size([1000, 1536]).
	size mismatch for blocks.1.0.bn2.gain.weight: copying a param with shape torch.Size([768, 148]) from checkpoint, the shape in current model is torch.Size([1000, 768]).
	size mismatch for blocks.1.0.bn2.bias.weight: copying a param with shape torch.Size([768, 148]) from checkpoint, the shape in current model is torch.Size([1000, 768]).
	size mismatch for blocks.2.0.bn1.gain.weight: copying a param with shape torch.Size([768, 148]) from checkpoint, the shape in current model is torch.Size([1000, 768]).
	size mismatch for blocks.2.0.bn1.bias.weight: copying a param with shape torch.Size([768, 148]) from checkpoint, the shape in current model is torch.Size([1000, 768]).
	size mismatch for blocks.2.0.bn2.gain.weight: copying a param with shape torch.Size([384, 148]) from checkpoint, the shape in current model is torch.Size([1000, 384]).
	size mismatch for blocks.2.0.bn2.bias.weight: copying a param with shape torch.Size([384, 148]) from checkpoint, the shape in current model is torch.Size([1000, 384]).
	size mismatch for blocks.3.0.bn1.gain.weight: copying a param with shape torch.Size([384, 148]) from checkpoint, the shape in current model is torch.Size([1000, 384]).
	size mismatch for blocks.3.0.bn1.bias.weight: copying a param with shape torch.Size([384, 148]) from checkpoint, the shape in current model is torch.Size([1000, 384]).
	size mismatch for blocks.3.0.bn2.gain.weight: copying a param with shape torch.Size([192, 148]) from checkpoint, the shape in current model is torch.Size([1000, 192]).
	size mismatch for blocks.3.0.bn2.bias.weight: copying a param with shape torch.Size([192, 148]) from checkpoint, the shape in current model is torch.Size([1000, 192]).
	size mismatch for blocks.4.0.bn1.gain.weight: copying a param with shape torch.Size([192, 148]) from checkpoint, the shape in current model is torch.Size([1000, 192]).
	size mismatch for blocks.4.0.bn1.bias.weight: copying a param with shape torch.Size([192, 148]) from checkpoint, the shape in current model is torch.Size([1000, 192]).
	size mismatch for blocks.4.0.bn2.gain.weight: copying a param with shape torch.Size([96, 148]) from checkpoint, the shape in current model is torch.Size([1000, 96]).
	size mismatch for blocks.4.0.bn2.bias.weight: copying a param with shape torch.Size([96, 148]) from checkpoint, the shape in current model is torch.Size([1000, 96]).`

I am trying to reverse engineer the hyperparameters, but it would be really nice if you would provide the parameters used to train the pre-trained models available for download. That is what I have so far:

`parser.add_argument(
    '--dataset', type=str,
    default='I128_hdf5',
    help='Which Dataset to train on, out of I128, I256, C10, C100;'
         'Append "_hdf5" to use the hdf5 version for ISLVRC '
         '(default: %(default)s)')
  parser.add_argument(
    '--augment', action='store_true', default=False,
    help='Augment with random crops and flips (default: %(default)s)')
  parser.add_argument(
    '--num_workers', type=int, default=8,
    help='Number of dataloader workers; consider using less for HDF5 '
         '(default: %(default)s)')
  parser.add_argument(
    '--no_pin_memory', action='store_false', dest='pin_memory', default=True,
    help='Pin data into memory through dataloader? (default: %(default)s)') 
  parser.add_argument(
    '--shuffle', action='store_true', default=False,
    help='Shuffle the data (strongly recommended)? (default: %(default)s)')
  parser.add_argument(
    '--load_in_mem', action='store_true', default=False,
    help='Load all data into memory? (default: %(default)s)')
  parser.add_argument(
    '--use_multiepoch_sampler', action='store_true', default=False,
    help='Use the multi-epoch sampler for dataloader? (default: %(default)s)')

  ### Model stuff ###
  parser.add_argument(
    '--model', type=str, default='BigGAN',
    help='Name of the model module (default: %(default)s)')
  parser.add_argument(
    '--G_param', type=str, default='SN',
    help='Parameterization style to use for G, spectral norm (SN) or SVD (SVD)'
          ' or None (default: %(default)s)')
  parser.add_argument(
    '--D_param', type=str, default='SN',
    help='Parameterization style to use for D, spectral norm (SN) or SVD (SVD)'
         ' or None (default: %(default)s)')    
  parser.add_argument(
    '--G_ch', type=int, default=96, #  default=64, CHANGED FOR MODEL LOADING
    help='Channel multiplier for G (default: %(default)s)')
  parser.add_argument(
    '--D_ch', type=int, default=96, #  default=64, CHANGED FOR MODEL LOADING
    help='Channel multiplier for D (default: %(default)s)')
  parser.add_argument(
    '--G_depth', type=int, default=1,
    help='Number of resblocks per stage in G? (default: %(default)s)')
  parser.add_argument(
    '--D_depth', type=int, default=1,
    help='Number of resblocks per stage in D? (default: %(default)s)')
  parser.add_argument(
    '--D_thin', action='store_false', dest='D_wide', default=True,
    help='Use the SN-GAN channel pattern for D? (default: %(default)s)')
  parser.add_argument(
    '--G_shared', action='store_true', default=False,
    help='Use shared embeddings in G? (default: %(default)s)')
  parser.add_argument(
    '--shared_dim', type=int, default=0,
    help='G''s shared embedding dimensionality; if 0, will be equal to dim_z. '
         '(default: %(default)s)')
  parser.add_argument(
    '--dim_z', type=int, default=20, # default=128, CHANGED FOR MODEL LOADING
    help='Noise dimensionality: %(default)s)')
  parser.add_argument(
    '--z_var', type=float, default=1.0,
    help='Noise variance: %(default)s)')    
  parser.add_argument(
    '--hier', action='store_true', default=False,
    help='Use hierarchical z in G? (default: %(default)s)')
  parser.add_argument(
    '--cross_replica', action='store_true', default=False,
    help='Cross_replica batchnorm in G?(default: %(default)s)')
  parser.add_argument(
    '--mybn', action='store_true', default=False,
    help='Use my batchnorm (which supports standing stats?) %(default)s)')
  parser.add_argument(
    '--G_nl', type=str, default='relu',
    help='Activation function for G (default: %(default)s)')
  parser.add_argument(
    '--D_nl', type=str, default='relu',
    help='Activation function for D (default: %(default)s)')
  parser.add_argument(
    '--G_attn', type=str, default='64',  # default='64', ????? 32, 64 OR 32_64  ??????
    help='What resolutions to use attention on for G (underscore separated) '
         '(default: %(default)s)')
  parser.add_argument(
    '--D_attn', type=str, default='64', ????? 32, 64 OR 32_64  ??????
    help='What resolutions to use attention on for D (underscore separated) '
         '(default: %(default)s)')
  parser.add_argument(
    '--norm_style', type=str, default='bn',
    help='Normalizer style for G, one of bn [batchnorm], in [instancenorm], '
         'ln [layernorm], gn [groupnorm] (default: %(default)s)')`

**Comment by ajbrock** [comment]
The hyperparameters for this checkpoint are those used in the [main launch script](https://github.com/ajbrock/BigGAN-PyTorch/blob/master/scripts/launch_BigGAN_bs256x8.sh).
