### ISSUE TITLE
Output images have holes in them

### ISSUE THREAD

**Issue by christegho** [ajbrock/BigGAN-PyTorch#35]
I have been training my own models with 256x256 outputs, using my own dataset, with 1 class only. The training is working as expected, but I keep noticing the outputs from the GAN have holes in them. See example below.

Initially I thought it is a matter of training for longer, or rather that the training data is not very clean. But when I tried the same with a different cleaner dataset (for a different class), I still noticed a hole in all the outputs, even after training for longer. 

I am using 4 GPUs, with a batch size of 40 and `--num_G_accumulations 4 --num_D_accumulations 4`.

**I am wondering if anyone ran in the same issue? and what could be the problem?**

I included an example below: you can see the hole in the center of the image.

![image](https://user-images.githubusercontent.com/7484421/60254550-11bc2400-98c6-11e9-8b9c-76d094a34b60.png)

**Comment by tang-hy** [comment]
> I have been training my own models with 256x256 outputs, using my own dataset, with 1 class only. The training is working as expected, but I keep noticing the outputs from the GAN have holes in them. See example below.
> 
> Initially I thought it is a matter of training for longer, or rather that the training data is not very clean. But when I tried the same with a different cleaner dataset (for a different class), I still noticed a hole in all the outputs, even after training for longer.
> 
> I am using 4 GPUs, with a batch size of 40 and `--num_G_accumulations 4 --num_D_accumulations 4`.
> 
> **I am wondering if anyone ran in the same issue? and what could be the problem?**
> 
> I included an example below: you can see the hole in the center of the image.
> 
> ![image](https://user-images.githubusercontent.com/7484421/60254550-11bc2400-98c6-11e9-8b9c-76d094a34b60.png)

I have a bigger hole than yours......

**Comment by apoorvkh** [comment]
I am having the same issue -- samples from training (on my dataset of faces) seem to improve (though still low quality) for the first 2K iterations, but then there is a more distinct, dark hole in roughly the same spot in samples for all following iterations. Any solutions yet?

**Comment by apoorvkh** [comment]
I was able to solve this issue for training on my dataset by reducing the generator and discriminator learning rates to their defaults (respectively 5e-5, 2e-4).
