### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by ellismarte** [ajbrock/BigGAN-PyTorch#39]
Hi,

I'm running ./scripts/launch_BigGAN_bs256x8.sh and getting the following error: 

RuntimeError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 7.44 GiB total capacity; 5.47 GiB already allocated; 487.56 MiB free; 1.07 GiB cached)
 @ellismarte
 
Is there something I can configure so that that much memory doesn't get used and I don't run out of memory?

**Comment by ajbrock** [comment]
You can make the models smaller with either or both the `--G_ch` and `--D_ch` args, or you can use a smaller batch size. Be aware that this will likely negatively impact model performance. I train these models on 8xV100s with 16GB vram each--you likely won't be able to fit a very large batch size on a single 8GB gpu. You can slightly mollify this by paying the time cost of turning up the number of gradient accumulations.

**Comment by jakubLangr** [comment]
Great implementation! 

Just a comment on this:

On AWS, this implementation runs out of memory on V100s and for some reason only fully loads the first GPU. Perhaps GCP's implementation is somewhat different and has marginally smaller overhead running their nvidia-docker. 

Any thoughts on this @ajbrock ?

**Comment by ajbrock** [comment]
Hi Jakub,

With the standard `nn.DataParallel` implementation in this code the first GPU does tend to have a slightly higher memory usage for a variety of reasons (I think sampling might still incur a high VRAM cost). It's never been an issue for me during training, though, and I don't think it's ever been more than like a gig of difference. The way the `G_D` module is set up should do a lot to minimize this artifact.

Also note that I don't use docker or GCP, I use conda environments on an inter-university server.


Just sanity checking, what batch size, image size, `num_accumulations,` and model size (`G_ch`, `D_ch`, and deep vs non-deep) are you using, along with how many V100s, memory per V100, and CUDA/CUDNN/PyTorch versions they're on? There's a lot of variables for this kind of thing. 

Also, just a general debugging tip, if you're running out of memory, the easiest way to see the limit is to start with a small batch size (1 or 2 per device) and crank it up until things run out.

**Comment by jakubLangr** [comment]
Hi, thank you for a very prompt response on a Saturday!

The whole process fails with batch size of 60, but succeeds at 2 and 32. But as increasing batch_size was a big reason for the success of your paper, I would love to see if I can get this resolved. What versions did you use?

I am using the defaults in train.py (other than `--parallel`) to minimize likelihood it is just me being dumb.

As per docs,
```
In [2]: torch.__version__
Out[2]: '1.0.1'
```

*CUDA*
Cuda compilation tools, release 9.0, V9.0.176

*CuDNN*
```
(pytorch_p36) ubuntu@aws:/experiments/BigGAN-PyTorch$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 3
#define CUDNN_PATCHLEVEL 1
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```

Output of `nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:17.0 Off |                    0 |
| N/A   50C    P0    47W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:18.0 Off |                    0 |
| N/A   52C    P0    47W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:19.0 Off |                    0 |
| N/A   53C    P0    50W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:1A.0 Off |                    0 |
| N/A   50C    P0    46W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   53C    P0    48W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   57C    P0    48W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   52C    P0    51W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   51C    P0    45W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by ajbrock** [comment]
Hi Jakub,

To clarify, are you using `--parallel` or not? If you don't use `--parallel`, you will not use all of the GPUs. Also, just to be clear, this is a GAN, not a likelihood based model (JSD maybe-equivalences aside).

**Comment by jakubLangr** [comment]
Yes, I am using all the defaults except `--parallel`, which I think is what the problem was originally. I think then I had to reset GPU memory, but after that it seems to work.

**Comment by ajbrock** [comment]
Great! For future reference, the default script is for an overall batch size of 256, meaning a batch size of 32 per device. If you weren't running with `--parallel`, then the OOM you experienced past BS=32 on a single device is expected.

**Comment by SonNNguyen** [comment]
Hi @ajbrock thanks for your such great work. Can you suggest a rough idea of how much should I change the channel number in G and D? just for the purpose of increase batch size as much as possible.
I train on custom dataset with 2080 ti 11GB and my dataset is single-class. So probably I dont need that much of the whole full network performance. I would love to have your advice on network structure and batch size tradeoff. Thank you alot
