### ISSUE TITLE
Why drop_last of DataLoader is disabled

### ISSUE THREAD

**Issue by RuiLiFeng** [ajbrock/BigGAN-PyTorch#42]
I cut the num_works to 0 due to lack of RAM and run BigGAN_bs256x8.sh, ended up with error bellow
![image](https://user-images.githubusercontent.com/33709183/64478464-77d4f980-d1db-11e9-8dc2-2485cb5e7012.png)
I noticed that it was processing the last batch in the first epoch, so I dug into the dataloader part, and I found that drop_last is disabled when use_multiepoch_sampler is enabled, would that cause tuple error as I meet?

**Comment by RuiLiFeng** [comment]
Also could the authors be so nice to offer pretrained biggan deep?

**Comment by zxhuang97** [comment]
I also encountered this bug after modifying the batch size. You can either set  drop_last = True, or increase the num_epoch so it won't come across the last batch of data.

**Comment by RuiLiFeng** [comment]
@Killer97 Thank you for your advice！
