### ISSUE TITLE
Should not `import model`

### ISSUE THREAD

**Issue by SsnL** [ajbrock/BigGAN-PyTorch#7]
https://github.com/ajbrock/BigGAN-PyTorch/blob/a5557079924c3070b39e67f2eaea3a52c0fb72ab/sample.py#L21

This causes `ModuleNotFound`. I believe the importing of model module is covered below with `__import__`.

**Comment by ajbrock** [comment]
Good catch, thanks! Fixed with [this commit](https://github.com/ajbrock/BigGAN-PyTorch/commit/0ce9a43050068ab2634ee9fb6d1379bdbd3c9416)
