### ISSUE TITLE
Number of parameter doesn't match the paper; plus `init_weights` doesn't initialize bias weights

### ISSUE THREAD

**Issue by ParthaEth** [ajbrock/BigGAN-PyTorch#78]
In table 1 of the original paper - 'Large Scale GAN Training for High Fidelity Natural Image Synthesis' the authors claim number of parameters to be in the range of 80M while this repository reports only about 4.3M parameters for 32X32 images i.e. CIFAR-10 images. Do anyone know where this discrepancy is cropping in from?

Also the `init_weights` function in the BigGAN.py only initializes the weight parameters. One should also initialize the bias parameters.

Finally I fail to assert which dataset Table1 of the the original paper - `'Large Scale GAN Training for High Fidelity Natural Image Synthesis'` refers to.

**Comment by ajbrock** [comment]
> Param nums

Reported parameter counts are for models at the relevant resolutions. Models for lower resolutions have fewer layers, can be less wide, and therefore have fewer parameters.

> init_weights

The biases are already zero-initialized, there's no need to override their inits.

> table 1

Table 1 is for ImageNet, the primary dataset used in the paper.
