### ISSUE TITLE
Correct attention layer implementation

### ISSUE THREAD

**Issue by valillon** [ajbrock/BigGAN-PyTorch#88]
There is an interesting [comment](https://github.com/ajbrock/BigGAN-PyTorch/blob/98459431a5d618d644d54cd1e9fceb1e5045648d/layers.py#L142) regarding the original attention layer proposed in SAGAN. Actually, the published method and the actual implementation significantly differ as issued in the [official repo](https://github.com/brain-research/self-attention-gan/issues/30) and another well-known [pytorch implementation](https://github.com/heykeetae/Self-Attention-GAN/issues/54). Therein, I recently proposed an implementation which strictly follows the original paper description, at least to my understanding of it.

So, with not other explanation, which is then the correct method, the one published or the implemented one?

**Comment by ajbrock** [comment]
The SAGAN source code is the source of truth; where it differs from the paper, the source code is correct.

**Comment by valillon** [comment]
So it be.
Any reason for those `max_pool2d()` inside the attention layer, apart from saving computation?

**Comment by ajbrock** [comment]
Design-wise, yep, it's just for compute. You can downsample the keys and values without much loss in quality but while improving compute/memory overhead.

**Comment by valillon** [comment]
Good to know.
Thanks for the hint Andy!
