### ISSUE TITLE
Do you have any plan to release the 256 and 512 pre-trained models?

### ISSUE THREAD

**Issue by MilanKolkata** [ajbrock/BigGAN-PyTorch#9]
Hi ajbrock,
I believe the most attractive part of BigGAN is generating the high-resolution images. Do you have any plan to release the 256 and 512 pre-trained models?
Thanks.

**Comment by ajbrock** [comment]
We include code for porting the TFHub pretrained models at all resolutions, and we are currently considering training 256x256 models with this codebase but haven't decided on anything yet.

**Comment by IceClear** [comment]
> We include code for porting the TFHub pretrained models at all resolutions, and we are currently considering training 256x256 models with this codebase but haven't decided on anything yet.

@ajbrock Hi. May I know if the pretrained models on 256 and 512 are available?
